### ISSUE TITLE
How to get an Instance of KeyManager?

### ISSUE THREAD

**Issue by schulzh** [cloudfoundry/java-buildpack-security-provider#6]
I need to configure a reactive HTTP client with an instance of KeyManager, such that calls can be made using the [Instance Identity Credentials](https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html).

In a similar request, #2, it was recommended to use the default SSLContext, that gets picked up by most clients automatically. This does not seem to be the case for Reactor-Netty however, probably because it uses a different type of SSLContext (`io.netty.handler.ssl` vs `javax.net.ssl`).

I'm therefore trying to configure the Netty SSLContext by passing an Instance of KeyManager manually, but obtaining this instance proves very difficult. I have found a way to get an instance using reflections that works, but cannot be the intended way:
```java
KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());

Field factorySpiField = KeyManagerFactory.class.getDeclaredField("factorySpi");
factorySpiField.setAccessible(true);
KeyManagerFactorySpi kmfSpi = (KeyManagerFactorySpi) factorySpiField.get(kmf);

if (!kmfSpi.getClass().getName()
        .equals("org.cloudfoundry.security.CloudFoundryContainerKeyManagerFactory$SunX509"))
    throw new RuntimeException("KeyManagerFactorySpi is not of expected type for cloud foundry");

Method getContainerKeyManagerMethod = Class
        .forName("org.cloudfoundry.security.CloudFoundryContainerKeyManagerFactory")
        .getDeclaredMethod("getContainerKeyManager");
getContainerKeyManagerMethod.setAccessible(true);
X509ExtendedKeyManager keyManager = (X509ExtendedKeyManager) getContainerKeyManagerMethod.invoke(kmfSpi);

SslContextBuilder sslCtxBuilder = SslContextBuilder.forClient().keyManager(keyManager);

HttpClient httpClient = HttpClient.create();
httpClient = httpClient.secure(builder -> builder.sslContext(sslCtxBuilder));
```
What is the correct (or intended) method of obtaining this instance?

**Comment by dmikusa-pivotal** [comment]
OK, I'm not 100% sure how to answer your question but have a few suggestions to get started.

1. According to the [Reactor Netty docs](https://projectreactor.io/docs/netty/release/reference/index.html#_ssl_and_tls_4) it is going to use the OpenSSL provider by default. Given that, I do not believe the automatic TLS configuration facilities provided by the security provider will apply. Those are very specific to the Java TLS stack. 

2. The same doc link shows how you can switch to using the JDK as a TLS provider instead of OpenSSL. I haven't tried it, but I think that would be the first step to making things work. My suggestion would be to switch to using the JDK as the TLS provider as documented & then just try it without any additional configuration. It's possible that because you're using the JDK for TLS support & because the security provider configures that automatically that things may just work. I haven't tested it, but it seems plausible.

3. If things don't "just work" with step #2, or you want to use OpenSSL as the TLS provider, then I think you're going to need to manually configure TLS to use the instance id cert & key. As documented, you'll need to use the [SslContextBuilder](https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html) to configure TLS, then pass that into the HttpClient you create, like in the doc link for #1.

If you can, give that a try and report back if it helps/what happens.

**Comment by schulzh** [comment]
A colleague of mine found the solution, the trick is to specify the provider `Cloud Foundry Container` when querying the SPI and to initialize the `KeyManagerFactory` with `null` as the `KeyStore`:
```java
KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance("NewSunX509",
        "Cloud Foundry Container");
keyManagerFactory.init(null, null);
KeyManager[] keyManagers = keyManagerFactory.getKeyManagers();
if (keyManagers.length < 1) {
    throw new IllegalStateException("Cloud Foundry key manager factory didn't return any key managers");
}
if (keyManagers.length > 1) {
    log.warn("Cloud Foundry key manager factory returned multiple key managers: {}",
            getClassNames((Object[]) keyManagers));
}
KeyManager keyManager = keyManagers[0];
log.info("Using Cloud Foundry key manager: {}", keyManager.getClass().getName());

SslContextBuilder sslCtxBuilder = SslContextBuilder.forClient().keyManager(keyManager);

HttpClient httpClient = HttpClient.create().secure(builder -> builder.sslContext(sslCtxBuilder));
```
